// voting_next/pages/cadastro.tsx
import Nav from "../components/navBar";
import { useState } from 'react';
import { apiVoting } from '../apis';
import Guard from "../components/guardLogin";


function Cadastro() {
    const [name, setName] = useState('');
    const [email, setEmail] = useState('');
    const [password, setPassword] = useState('');
    const [confirme, setConfirme] = useState('');

    const [renderPage, setRenderPage] = useState(false);
    
    Guard(0).then((re: boolean) => {
        if (re){
            setRenderPage(re)
        }
    })

    const cadastrar = (e) => {
        e.preventDefault();

        if (password != confirme){
            return alert("Senhas não conferem")
        }

        apiVoting.post("/cadastro", {
            name: name,
            email: email,
            password: password,
        })
            .then(re => {
                if (re.data.token){
                    localStorage.setItem('token', re.data.token)
                    window.location.href = "/home"
                }
                
                else{
                    alert(re.data)
                }
            })
    }

    return renderPage &&
        <> 
            <Nav colors="#fff" itens={[
                {
                    type: "a",
                    text: "Home",
                    link: "/"
                },
                {
                    type: "button",
                    text: "Login",
                    link: "/login",
                    icon: "vi-login"
                }
            ]}></Nav>

            <main className="h-100">
                <div className="grid grid__2 h-100">
                    <div className="loginImgVote"></div>
                    <form className="flex__column flex__align__center flex__justify__center" onSubmit={cadastrar}>
                        <div className="w-50">
                            <h3 className="padb-2">Fazer cadastro</h3>
                            <div className="input__hero__label padb-1 w-100">
                                <input className="input w-100" type="text" placeholder=" " required value={name} onChange={e => setName(e.target.value)}/>
                                <label>Nome</label>
                            </div>

                            <div className="input__hero__label padb-1 w-100">
                                <input className="input w-100" type="email" placeholder=" " required value={email} onChange={e => setEmail(e.target.value)}/>
                                <label>Email</label>
                            </div>

                            <div className="input__hero__label padb-1 w-100">
                                <input className="input w-100" type="password" placeholder=" " required value={password} onChange={e => setPassword(e.target.value)}/>
                                <label>Senha</label>
                            </div>

                            <div className="input__hero__label padb-1 w-100">
                                <input className="input w-100" type="password" placeholder=" " required value={confirme} onChange={e => setConfirme(e.target.value)}/>
                                <label>Confirme</label>
                            </div>

                            <button className="pub">Fazer cadastro</button>
                            <div className="w-100">
                            </div>
                        </div>
                    </form>
                </div>
            </main>
        </>
}

export default Cadastro;

// voting_vue/src/views/cadastro.vue
<template>
    <div class="hv-100">
        <NavBar colors="#fff" :itensChildren="[
            {type: 'a', link: '/', text: 'Home'},
            {type: 'button', link: '/login', text: 'Login'},
        ]"></NavBar>

        <main>
            <div class="grid grid__2 h-100">
                <div class="loginImg"></div>
                <form class="flex__column flex__align__center flex__justify__center" @submit.prevent="cadastrar">
                    <div class="w-50">
                        <h3 class="padb-2">Fazer cadastro</h3>
                        <div class="input__hero__label padb-1 w-100">
                            <input class="input w-100" type="text" v-model="name" placeholder=" " required>
                            <label>Nome</label>
                        </div>

                        <div class="input__hero__label padb-1 w-100">
                            <input class="input w-100" type="email" v-model="email" placeholder=" " required>
                            <label>Email</label>
                        </div>

                        <div class="input__hero__label padb-1 w-100">
                            <input class="input w-100" type="password" v-model="password" placeholder=" " required>
                            <label>Senha</label>
                        </div>

                        <div class="input__hero__label padb-1 w-100">
                            <input class="input w-100" type="password" v-model="againPassword" placeholder=" " required>
                            <label>Confirme</label>
                        </div>

                        <button class="pub" type="submit">Fazer cadastro</button>
                    </div>
                </form>
            </div>
        </main>
    </div>
</template>

<script>
    import { apiVoting } from '../apis';
    import NavBar from '@/components/navBar.vue';

    export default {
        components:{
            NavBar
        },

        data: () => {
            return {
                name: '',
                email: '',
                password: '',
                againPassword: ''
            }
        },

        methods: {
            cadastrar() {
                if (this.password != this.againPassword){
                    return alert("As senhas não conferem")
                }   

                apiVoting.post("/cadastro", {
                    name: this.name,
                    email: this.email,
                    password: this.password,
                })
                    .then(re => {
                        if (re.data.token){
                            localStorage.setItem('token', re.data.token)
                            window.location.href = "/home"
                        }
                        
                        else{
                            alert(re.data)
                        }
                    })
            }
        }
    };
</script>

<style lang="scss" scoped>
    div.banner{
        max-width: 100%;
        height: 100vh;
    }

    div.loginImg{
        background-image: url("../assets/img/vote.jpg");
        height: 100%;
        background-size: cover;
        background-position: center;
    }
</style>
