// voting_next/components/navBar.tsx
function Nav(){
    return (
        <nav className="top__menu" style={{backgroundColor: "white"}}>
            <span></span>
            <ul>
                {/* <router-link to="/login"> */}
                    <button className="pub only__border">Fazer login</button>
                {/* </router-link> */}
            </ul>
        </nav>
    )
}

export default Nav;

// voting_vue/src/components/navBar.vue
<template>
    <nav class="top__menu" :style="'background-color:' + colors">
        <span></span>
        <ul>
            <router-link to="/login">
                <button class="pub only__border">Fazer login</button>
            </router-link>
        </ul>
    </nav>
</template>

<script>
    export default {
        props: {
            colors: {
                type: String,
                default: '#fff'
            }
        }
    };
</script>
